// <auto-generated />
namespace LinkedIn_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intial222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial222));
        
        string IMigrationMetadata.Id
        {
            get { return "201903061826253_intial222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
